Support Python 3.11-3.14, drop Python 3.7-3.8 (#60)
* Support Python 3.11-3.14, drop Python 3.7-3.8

* Test the newest and oldest supported versions of Python

* Set python_version to 3 in Pipfile

* Enable running linters for two python versions

* Test CI after changes

* Revert after CI test

* Add python_requires to the setup.py file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,21 +6,26 @@ on:
   - pull_request
 
 jobs:
-  test:
+  lint:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version:
+          - "3.9"
+          - "3.14"
     steps:
       - name: Checking out code from GitHub
         uses: actions/checkout@v5
 
-      - name: Set up Python 3.10
+      - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v6
         with:
-          python-version: '3.10'
+          python-version: ${{ matrix.python-version }}
 
       - uses: actions/cache@v4
         with:
           path: ~/.cache/pip
-          key: pip-${{ hashFiles('**/Pipfile.lock') }}
+          key: pip-${{ hashFiles('**/Pipfile.lock') }}-${{ matrix.python-version }}
           restore-keys: |
             pip-
 
@@ -32,6 +37,18 @@ jobs:
       - name: Run linters
         run: pipenv run make
 
+  test:
+    runs-on: ubuntu-latest
+    needs: [lint]
+    if: always()
+    steps:
+      - name: Check lint results
+        run: |
+          if [[ "${{ needs.lint.result }}" != "success" ]]; then
+            echo "Lint failed"
+            exit 1
+          fi
+
   publish:
     name: Publish a Python distribution to PyPI
     runs-on: ubuntu-latest
@@ -40,10 +57,10 @@ jobs:
     steps:
       - name: Checking out code from GitHub
         uses: actions/checkout@v5
-      - name: Set up Python 3.10
+      - name: Set up Python 3.14
         uses: actions/setup-python@v6
         with:
-          python-version: '3.10'
+          python-version: '3.14'
       - uses: actions/cache@v4
         with:
           path: ~/.cache/pip
